name: Test wordPattern
on:
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: Test wordPattern
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python 
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.9
      
      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
          echo "$env:APPDATA\Python\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Install dependencies
        run: |
          cd test_repo
          poetry install
      
      - name: Run tests
        run: |
          poetry run nosetests tests\test_biyection.py